services:
  postgres:
    image: postgres:15
    container_name: userservice-postgres
    environment:
      POSTGRES_DB: userservice_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - userservice-network

  redis:
    image: redis:7-alpine
    container_name: userservice-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - userservice-network

  app:
    build: .
    container_name: userservice-app
    depends_on:
      - postgres
      - redis
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/userservice_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: securityTokenForTheTaskMircoServices123321
    ports:
      - "8080:8080"
    networks:
      - userservice-network

volumes:
  postgres_data:
  redis_data:

networks:
  userservice-network:
    driver: bridge
