server.port=8080
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/userservice_db}
spring.datasource.username=${DB_USERNAME:karalina}
spring.datasource.password=${DB_PASSWORD:karalina}
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yml
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
