server.port=8080
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yml
spring.data.redis.host=localhost
spring.data.redis.port=6379